// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSvHq5m2xRGzuqvnorB1gLIrQuT0GEy60',
    appId: '1:315430993873:web:f7e0addcbb0bef87bdaaf0',
    messagingSenderId: '315430993873',
    projectId: 'loneliness-92e07',
    authDomain: 'loneliness-92e07.firebaseapp.com',
    storageBucket: 'loneliness-92e07.firebasestorage.app',
    measurementId: 'G-RN5YB11CPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFaN3Ss0xEFhw8nV6MxxuIK-rG51s_cHA',
    appId: '1:315430993873:android:898c93af069c8fe9bdaaf0',
    messagingSenderId: '315430993873',
    projectId: 'loneliness-92e07',
    storageBucket: 'loneliness-92e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3i3nGQ8oWonVG91fZfBgzSmJdffSxwY',
    appId: '1:315430993873:ios:a4645ff31248cec7bdaaf0',
    messagingSenderId: '315430993873',
    projectId: 'loneliness-92e07',
    storageBucket: 'loneliness-92e07.firebasestorage.app',
    iosBundleId: 'com.example.loneliness',
  );
}
